---
- name: Patch Red Hat-based VMs
  hosts: localhost
  vars:
    p_nodelist: "{{ patch_hosts }}"
  tasks:
    - name: Add dynamic entry
      ansible.builtin.add_host:
        name: "{{ item }}"
        group: temphost
      with_items: "{{ p_nodelist }}"
- name: This Playbook will update the server with latest patches
  hosts: temphost
  gather_facts: true
  become: true
  tasks:
    - name: Setup
      ansible.builtin.setup: null
      register: setup
    - name: Checking current kernel version of the host before patching
      ansible.builtin.command: uname -r
      register: kernel_before_patch
      changed_when: false
    - name: Check root filesystem space
      ansible.builtin.shell: |
        set -o pipefail
        df / --output=pcent | tail -n 1
      register: disk_usage
      changed_when: false
    - name: Fail if root filesystem is 100% full
      ansible.builtin.fail:
        msg: Root filesystem is 100% full, patching cannot be performed.
      when: disk_usage.stdout_lines == "100"
    - name: Check connectivity between patching host and RMT server
      ansible.builtin.wait_for:
        host: dest-testreposp7.itc.global.mahle
        port: 8383
        timeout: 10
      register: port_check
      ignore_errors: true
    - name: Stop if RMT and Target server Connectivity not established.
      ansible.builtin.fail:
        msg: "Cannot procced with patching: dest-testreposp7.itc.global.mahle :8383 is
          not reachable from {{ inventory_hostname }}"
      when: port_check is failed
    - name: Backup /etc/zypp/repos.d
      ansible.builtin.copy:
        src: /etc/zypp/repos.d
        dest: /etc/zypp/repos.d.backup_{{ ansible_date_time.date }}
        remote_src: true
        mode: preserve
    - name: Remove lock file from server to enable server register with RMT.
      ansible.builtin.copy:
        src: /etc/sysconfig/rhn/systemid
        dest: /var/tmp/systemid
        remote_src: true
        mode: preserve
    - name: Delete lock file from server
      ansible.builtin.file:
        path: /etc/sysconfig/rhn/systemid
        state: absent
    - name: Create SUSEConnect file
      ansible.builtin.file:
        path: /etc/SUSEConnect
        state: touch
        owner: root
        group: root
        mode: "0755"
    - name: Add URL info to SUSE Connect file to register with RMT
      ansible.builtin.copy:
        dest: /etc/SUSEConnect
        content: |
          ---
          url: http://dest-testreposp7.itc.global.mahle:8383
        owner: root
        group: root
        mode: "0644"
    - name: Unset proxy variables
      ansible.builtin.command: unset HTTP_PROXY HTTPS_PROXY NO_PROXY http_proxy https_proxy no_proxy
      args:
        executable: /bin/bash
      changed_when: false
    - name: Register the system with RMT sever using SUSEConnect
      ansible.builtin.command: SUSEConnect
      changed_when: false
    - name: Activate extensions modules in system
      ansible.builtin.command: SUSEConnect -p {{ item }}
      loop:
        - sle-module-basesystem/15.7/x86_64
        - sle-module-desktop-applications/15.7/x86_64
        - sle-module-development-tools/15.7/x86_64
        - sle-module-server-applications/15.7/x86_64
        - sle-module-web-scripting/15.7/x86_64
        - sle-module-legacy/15.7/x86_64
        - sle-module-public-cloud/15.7/x86_64
        - sle-module-confidential-computing/15.7/x86_64
        - sle-module-containers/15.7/x86_64
        - sle-module-transactional-server/15.7/x86_64
        - sle-module-python3/15.7/x86_64
        - sle-module-systems-management/15.7/x86_64
        - PackageHub/15.7/x86_64
        - sle-module-certifications/15.7/x86_64
      register: suseconnect_out
      changed_when: false
    - name: Clean repository acche
      ansible.builtin.command: zypper clean -a
      changed_when: false
    - name: Update system using only BaseOS and Appstream
      community.general.zypper:
        name: "*"
        state: latest
      register: zypp_result
    - name: Checking the new updated kernel version on SUSE server
      ansible.builtin.shell: |
        set -o pipefail
        rpm -qa | grep kernel| sort| tail -1 | awk -F- '{print $(NF -1)"-"$NF}'
      register: new_kernel
      changed_when: false
    - name: Wait for server to comeback online
      block:
        - name: Reboot SUSE server
          ansible.builtin.reboot:
            reboot_timeout: 300
          register: reboot_result
        - name: Wait for server to comeback online
          ansible.builtin.wait_for_connection:
            delay: 0
            timeout: 300
            sleep: 0
            connect_timeout: 5
          register: waitresult
          until: waitresult is success
          retries: 5
          delay: 6
        - name: Verify system after successful reboot
          ansible.builtin.command: uptime
          register: uptime_result
          changed_when: false
      rescue:
        - name: Debug if server is not up
          ansible.builtin.debug:
            msg: "{{ inventory_hostname }} is not up after 5 retries, Kindly check the
              server manually."
          when: wait_result != 0
    - name: Check if the system has rebooted successfully
      ansible.builtin.debug:
        msg: "System successfully rebooted. Uptime: {{ uptime_result.stdout }}"
      when: uptime_result.stdout is defined
    - name: Checking the updated kernel version on target hosts
      ansible.builtin.command: uname -r
      register: new_kernel
      changed_when: false
    - name: Display new kernel version of target host
      ansible.builtin.debug:
        msg: Latest kernel of system {{ inventory_hostname }} is {{ new_kernel.stdout }}
    - name: Debug Successful Patched servers
      ansible.builtin.debug:
        msg: Server {{ inventory_hostname }} was Patched successfully without any issue
      when:
        - zypp_result.changed
        - reboot_result is defined
        - uptime_result is defined
    - name: Display patch status for the server.
      ansible.builtin.debug:
        msg: >-
          {% set disk = disk_usage.stdout | regex_replace('[^0-9]', '') | int %} {%
          if disk > 90 %}
            Server {{ inventory_hostname }} has disk usage {{ disk_usage.stdout }}. Skipping patch due to high disk usage.
          {% elif zypp_result is failed %}
            Server {{ inventory_hostname }} encountered an error during zypp_update.
          {% elif zypp_result.changed and reboot_result is not defined %}
            Server {{ inventory_hostname }} did not rebooted properly after patching. Manual check needed.
          {% elif zypp_result.results is defined and zypp_result.results | length == 0 %}
            Patch result msg for {{ inventory_hostname }}: {{ zypp_result.msg | default() }}
          {% else %}
            Patch was successfully applied for {{ inventory_hostname }}
          {% endif %}
    - name: Remove current /etc/zypp.repos.d
      ansible.builtin.file:
        path: /etc/zypp/repos.d
        state: absent
      register: passed_hosts
    - name: Restore /etc/zypp.repos.d from backup
      ansible.builtin.copy:
        src: /etc/zypp/repos.d.backup_{{ ansible_date_time.date }}/repos.d
        dest: /etc/zypp/
        remote_src: true
        mode: preserve
    - name: Delete SUSEConnect file
      ansible.builtin.file:
        path: /etc/SUSEConnect
        state: absent
    - name: Initiate task failure
      ansible.builtin.set_fact:
        repos_reverted: false
    - name: Mark hosts as successfull.
      ansible.builtin.set_fact:
        repos_reverted: true
      when:
        - passed_hosts is succeeded
        - passed_hosts.changed
    - name: Debug complaince
      ansible.builtin.debug:
        msg:
          patch_db_patch_compliance_update:
            - vm_name: "{{ inventory_hostname }}"
            - change_number: "{{ change_number }}"
            - version: "15.7"
            - kernel_version: "{{ new_kernel.stdout if new_kernel.stdout is defined else
                kernel_before_patch.stdout }}"
            - last_patch_applied: "{{ ansible_date_time.iso8601 }}"
            - compliance: true
- name: Display final passed servers
  hosts: localhost
  gather_facts: true
  vars:
    successful_servers: []
  tasks:
    - name: Build list of successfullservers
      ansible.builtin.set_fact:
        successful_servers: "{{ successful_servers + [item] }}"
      loop: "{{ groups['temphost'] | default() }}"
      when:
        - hostvars[item].repos_reverted | default(false)
    - name: Build list of failed servers
      ansible.builtin.set_fact:
        failed_servers: "{{ failed_servers + [item] }}"
      loop: "{{ groups['temphost'] | default() }}"
      when:
        - not hostvars[item].repos_reverted | default(false)
    - name: Debug
      ansible.builtin.debug:
        msg:
          patched_hosts: "{{ successful_servers | default([]) | join(',') }}"
    - name: ServiceTheatre success update
      ansible.builtin.debug:
        msg:
          - "target_host : {{ groups['temphost'] | join(',') }}"
          - "task_name : Patching playbook for SUSE"
          - status_msg: >
              Patching completed successfully on - {{ successful_servers |
              default([]) | join(',') }}

              Patching was failed on - {{ failed_servers | default([]) | join(',') }}
          - "status : Success"
          - "execution_date_time : {{ ansible_date_time.iso8601 }}"
      when:
        - successful_servers | length > 0
    - name: ServiceTheatre failure update
      ansible.builtin.debug:
        msg:
          - "target_host  : {{ groups['temphost'] | join(',') }}"
          - "task_name : Patching playbook for SUSE"
          - "status_msg   : None of the servers patching was completed
            successfully"
          - "status : Failed"
          - "execution_date_time : {{ ansible_date_time.iso8601 }}"
      when:
        - successful_servers | length == 0
