---
- name: Add host to dynamic inventory
  hosts: localhost
  tasks:
    - name: Adding hosts to dynamic hosts
      ansible.builtin.add_host:
        name: "{{ var_ipadd }}"
        groups: dynamic_hosts
- name: Check OpsRamp Agent on Linux
  hosts: dynamic_hosts
  gather_facts: true
  tasks:
    - name: Check if OpsRamp Agent is installed
      block:
        - name: Show status of dcservice.service
          ansible.builtin.command: systemctl status opsramp-agent.service
          register: service_status
          changed_when: false
          ignore_errors: true
        - name: Display dcservice.service status
          ansible.builtin.debug:
            msg: "{{ service_status.stdout }}"
        - name: ServiceTheater Update for all tasks in installation status
          ansible.builtin.debug:
            msg:
              - "target_host        : {{ inventory_hostname | default('') }}"
              - "task_name          : OpsRamp agent installation status"
              - "status_msg         : OpsRamp agent is installed"
              - "status             : Success"
              - "execution_date_time: {{ ansible_date_time['iso8601'] }}"
      rescue:
        - name: ServiceTheater Failure Update for all tasks in installation status block
          ansible.builtin.debug:
            msg:
              - "target_host        : {{ inventory_hostname | default('') }}"
              - "task_name          : {{ ansible_failed_task['name'] }}"
              - "status_msg         : {{ ansible_failed_result['msg'] }}"
              - "status             : Failed"
              - "execution_date_time: {{ ansible_date_time['iso8601'] }}"
        - name: Failing the playbook if any task failed in the installation status
          ansible.builtin.fail:
            msg: Error during playbook execution please check the respective failed task for
              more information
