

    credentials:
    -   credential_type:
            kind: ssh
            name: Machine
            type: credential_type
        description: ''
        inputs:
            become_method: ''
            become_username: ''

            username: root
        name: Bhushan AWX Inventory
        natural_key:
            credential_type:
                kind: ssh
                name: Machine
                type: credential_type
            name: Bhushan AWX Inventory
            organization: null
            type: credential
        organization: null
        user:
            type: user
            username: admin
    -   credential_type:
            kind: scm
            name: Source Control
            type: credential_type
        description: ''
        inputs:

            username: bhushan3806
        name: Bit Bucket Creds
        natural_key:
            credential_type:
                kind: scm
                name: Source Control
                type: credential_type
            name: Bit Bucket Creds
            organization: null
            type: credential
        organization: null
        user:
            type: user
            username: admin
    -   credential_type:
            kind: ssh
            name: Machine
            type: credential_type
        description: ''
        inputs:
            become_method: ''
            become_username: ''

            username: root
        name: Demo Creds
        natural_key:
            credential_type:
                kind: ssh
                name: Machine
                type: credential_type
            name: Demo Creds
            organization: null
            type: credential
        organization: null
        user:
            type: user
            username: admin


...
